In [1]:
import pandas as pd
import numpy as np

In [2]:
circuits = pd.read_csv("circuits.csv", sep=',', encoding='latin-1')
constructorResults = pd.read_csv("constructorResults.csv", sep=',', encoding='latin-1')
constructors = pd.read_csv("constructors.csv", sep=',', encoding='latin-1')
constructorStandings = pd.read_csv("constructorStandings.csv", sep=',', encoding='latin-1')
drivers = pd.read_csv("drivers.csv", sep=',', encoding='latin-1')
driverStandings = pd.read_csv("driverStandings.csv", sep=',', encoding='latin-1')
lapTimes = pd.read_csv("lapTimes.csv", sep=',', encoding='latin-1')
pitStops = pd.read_csv("pitStops.csv", sep=',', encoding='latin-1')
qualifying = pd.read_csv("qualifying2.csv", sep=',', encoding='latin-1')
races = pd.read_csv("races.csv", sep=',', encoding='latin-1')
results = pd.read_csv("results.csv", sep=',', encoding='latin-1')
seasons = pd.read_csv("seasons.csv", sep=',', encoding='latin-1')
status = pd.read_csv("status.csv", sep=',', encoding='latin-1')

In [3]:
races

raceId  year  round  circuitId                      name        date  \
0         1  2009      1          1     Australian Grand Prix  2009-03-29   
1         2  2009      2          2      Malaysian Grand Prix  2009-04-05   
2         3  2009      3         17        Chinese Grand Prix  2009-04-19   
3         4  2009      4          3        Bahrain Grand Prix  2009-04-26   
4         5  2009      5          4        Spanish Grand Prix  2009-05-10   
5         6  2009      6          6         Monaco Grand Prix  2009-05-24   
6         7  2009      7          5        Turkish Grand Prix  2009-06-07   
7         8  2009      8          9        British Grand Prix  2009-06-21   
8         9  2009      9         20         German Grand Prix  2009-07-12   
9        10  2009     10         11      Hungarian Grand Prix  2009-07-26   
10       11  2009     11         12       European Grand Prix  2009-08-23   
11       12  2009     12         13        Belgian Grand Prix  2009-08-30   
12       13  2009     13         14        Italian Grand Prix  2009-09-13   
13       14  2009     14         15      Singapore Grand Prix  2009-09-27   
14       15  2009     15         22       Japanese Grand Prix  2009-10-04   
15       16  2009     16         18      Brazilian Grand Prix  2009-10-18   
16       17  2009     17         24      Abu Dhabi Grand Prix  2009-11-01   
17       18  2008      1          1     Australian Grand Prix  2008-03-16   
18       19  2008      2          2      Malaysian Grand Prix  2008-03-23   
19       20  2008      3          3        Bahrain Grand Prix  2008-04-06   
20       21  2008      4          4        Spanish Grand Prix  2008-04-27   
21       22  2008      5          5        Turkish Grand Prix  2008-05-11   
22       23  2008      6          6         Monaco Grand Prix  2008-05-25   
23       24  2008      7          7       Canadian Grand Prix  2008-06-08   
24       25  2008      8          8         French Grand Prix  2008-06-22   
25       26  2008      9          9        British Grand Prix  2008-07-06   
26       27  2008     10         10         German Grand Prix  2008-07-20   
27       28  2008     11         11      Hungarian Grand Prix  2008-08-03   
28       29  2008     12         12       European Grand Prix  2008-08-24   
29       30  2008     13         13        Belgian Grand Prix  2008-09-07   
..      ...   ...    ...        ...                       ...         ...   
967     980  2017     12         13        Belgian Grand Prix  2017-08-27   
968     981  2017     13         14        Italian Grand Prix  2017-09-03   
969     982  2017     14         15      Singapore Grand Prix  2017-09-17   
970     983  2017     15          2      Malaysian Grand Prix  2017-10-01   
971     984  2017     16         22       Japanese Grand Prix  2017-10-08   
972     985  2017     17         69  United States Grand Prix  2017-10-22   
973     986  2017     18         32        Mexican Grand Prix  2017-10-29   
974     987  2017     19         18      Brazilian Grand Prix  2017-11-12   
975     988  2017     20         24      Abu Dhabi Grand Prix  2017-11-26   
976     989  2018      1          1     Australian Grand Prix  2018-03-25   
977     990  2018      2          3        Bahrain Grand Prix  2018-04-08   
978     991  2018      3         17        Chinese Grand Prix  2018-05-15   
979     992  2018      4         73     Azerbaijan Grand Prix  2018-04-29   
980     993  2018      5          4        Spanish Grand Prix  2018-05-13   
981     994  2018      6          6         Monaco Grand Prix  2018-05-27   
982     995  2018      7          7       Canadian Grand Prix  2018-06-10   
983     996  2018      8         34         French Grand Prix  2018-06-24   
984     997  2018      9         70       Austrian Grand Prix  2018-07-01   
985     998  2018     10          9        British Grand Prix  2018-07-08   
986     999  2018     11         10         German Grand Prix  2018-07-22   
9

In [4]:
results

resultId  raceId  driverId  constructorId  number  grid  position  \
0             1      18         1              1    22.0     1       1.0   
1             2      18         2              2     3.0     5       2.0   
2             3      18         3              3     7.0     7       3.0   
3             4      18         4              4     5.0    11       4.0   
4             5      18         5              1    23.0     3       5.0   
5             6      18         6              3     8.0    13       6.0   
6             7      18         7              5    14.0    17       7.0   
7             8      18         8              6     1.0    15       8.0   
8             9      18         9              2     4.0     2       NaN   
9            10      18        10              7    12.0    18       NaN   
10           11      18        11              8    18.0    19       NaN   
11           12      18        12              4     6.0    20       NaN   
12           13      18        13              6     2.0     4       NaN   
13           14      18        14              9     9.0     8       NaN   
14           15      18        15              7    11.0     6       NaN   
15           16      18        16             10    20.0    22       NaN   
16           17      18        17              9    10.0    14       NaN   
17           18      18        18             11    16.0    12       NaN   
18           19      18        19              8    19.0    21       NaN   
19           20      18        20              5    15.0     9       NaN   
20           21      18        21             10    21.0    16       NaN   
21           22      18        22             11    17.0    10       NaN   
22           23      19         8              6     1.0     2       1.0   
23           24      19         9              2     4.0     4       2.0   
24           25      19         5              1    23.0     8       3.0   
25           26      19        15              7    11.0     3       4.0   
26           27      19         1              1    22.0     9       5.0   
27           28      19         2              2     3.0     5       6.0   
28           29      19        17              9    10.0     6       7.0   
29           30      19         4              4     5.0     7       8.0   
...         ...     ...       ...            ...     ...   ...       ...   
23747     23752     987       832              4    55.0     8      11.0   
23748     23753     987       842              5    10.0    19      12.0   
23749     23754     987       828             15     9.0    17      13.0   
23750     23755     987       836             15    94.0    15      14.0   
23751     23756     987       154            210     8.0    11      15.0   
23752     23757     987       840              3    18.0    16      16.0   
23753     23758     987       843              5    28.0    18       NaN   
23754     23759     987       839             10    31.0    10       NaN   
23755     23760     987       838              1     2.0    12       NaN   
23756     23761     987       825            210    20.0    13       NaN   
23757     23762     988       822            131    77.0     1       1.0   
23758     23763     988         1            131    44.0     2       2.0   
23759     23764     988        20              6     5.0     3       3.0   
23760     23765     988         8              6     7.0     5       4.0   
23761     23766     988       830              9    33.0     6       5.0   
23762     23767     988       807              4    27.0     7       6.0   
23763     23768     988       815             10    11.0     8       7.0   
23764     23769     988       839             10    31.0     9       8.0   
23765     23770     988         4              1    14.0    11       9.0   
23766     23771     988        13              3    19.0    10      10.0   
23767     23772     988       154            210     8.

In [5]:
results = results.merge(races, on='raceId', how='left')
len(results)

23777

In [6]:
fin = []
for row in results['position']:
    if row > 0:
        fin.append(int(1))
    else: fin.append(int(0))
results['fin'] = fin
results

resultId  raceId  driverId  constructorId  number  grid  position  \
0             1      18         1              1    22.0     1       1.0   
1             2      18         2              2     3.0     5       2.0   
2             3      18         3              3     7.0     7       3.0   
3             4      18         4              4     5.0    11       4.0   
4             5      18         5              1    23.0     3       5.0   
5             6      18         6              3     8.0    13       6.0   
6             7      18         7              5    14.0    17       7.0   
7             8      18         8              6     1.0    15       8.0   
8             9      18         9              2     4.0     2       NaN   
9            10      18        10              7    12.0    18       NaN   
10           11      18        11              8    18.0    19       NaN   
11           12      18        12              4     6.0    20       NaN   
12           13      18        13              6     2.0     4       NaN   
13           14      18        14              9     9.0     8       NaN   
14           15      18        15              7    11.0     6       NaN   
15           16      18        16             10    20.0    22       NaN   
16           17      18        17              9    10.0    14       NaN   
17           18      18        18             11    16.0    12       NaN   
18           19      18        19              8    19.0    21       NaN   
19           20      18        20              5    15.0     9       NaN   
20           21      18        21             10    21.0    16       NaN   
21           22      18        22             11    17.0    10       NaN   
22           23      19         8              6     1.0     2       1.0   
23           24      19         9              2     4.0     4       2.0   
24           25      19         5              1    23.0     8       3.0   
25           26      19        15              7    11.0     3       4.0   
26           27      19         1              1    22.0     9       5.0   
27           28      19         2              2     3.0     5       6.0   
28           29      19        17              9    10.0     6       7.0   
29           30      19         4              4     5.0     7       8.0   
...         ...     ...       ...            ...     ...   ...       ...   
23747     23752     987       832              4    55.0     8      11.0   
23748     23753     987       842              5    10.0    19      12.0   
23749     23754     987       828             15     9.0    17      13.0   
23750     23755     987       836             15    94.0    15      14.0   
23751     23756     987       154            210     8.0    11      15.0   
23752     23757     987       840              3    18.0    16      16.0   
23753     23758     987       843              5    28.0    18       NaN   
23754     23759     987       839             10    31.0    10       NaN   
23755     23760     987       838              1     2.0    12       NaN   
23756     23761     987       825            210    20.0    13       NaN   
23757     23762     988       822            131    77.0     1       1.0   
23758     23763     988         1            131    44.0     2       2.0   
23759     23764     988        20              6     5.0     3       3.0   
23760     23765     988         8              6     7.0     5       4.0   
23761     23766     988       830              9    33.0     6       5.0   
23762     23767     988       807              4    27.0     7       6.0   
23763     23768     988       815             10    11.0     8       7.0   
23764     23769     988       839             10    31.0     9       8.0   
23765     23770     988         4              1    14.0    11       9.0   
23766     23771     988        13              3    19.0    10      10.0   
23767     23772     988       154            210     8.

In [7]:
AGP = results[results['circuitId'] == 1]
AGP = results[results['dnftar'] == 0]
AGP = AGP.dropna()
AGP

resultId  raceId  driverId  constructorId  number  grid  position  \
0             1      18         1              1    22.0     1       1.0   
1             2      18         2              2     3.0     5       2.0   
2             3      18         3              3     7.0     7       3.0   
3             4      18         4              4     5.0    11       4.0   
4             5      18         5              1    23.0     3       5.0   
22           23      19         8              6     1.0     2       1.0   
23           24      19         9              2     4.0     4       2.0   
24           25      19         5              1    23.0     8       3.0   
25           26      19        15              7    11.0     3       4.0   
26           27      19         1              1    22.0     9       5.0   
27           28      19         2              2     3.0     5       6.0   
28           29      19        17              9    10.0     6       7.0   
29           30      19         4              4     5.0     7       8.0   
30           31      19        14              9     9.0    12       9.0   
31           32      19        18             11    16.0    11      10.0   
32           33      19        12              4     6.0    13      11.0   
44           45      20        13              6     2.0     2       1.0   
45           46      20         8              6     1.0     4       2.0   
46           47      20         9              2     4.0     1       3.0   
47           48      20         2              2     3.0     6       4.0   
48           49      20         5              1    23.0     5       5.0   
49           50      20        15              7    11.0     7       6.0   
50           51      20        17              9    10.0    11       7.0   
51           52      20         3              3     7.0     8       8.0   
52           53      20        10              7    12.0    13       9.0   
53           54      20         4              4     5.0    10      10.0   
54           55      20        22             11    17.0    12      11.0   
66           67      21         8              6     1.0     1       1.0   
67           68      21        13              6     2.0     3       2.0   
68           69      21         1              1    22.0     5       3.0   
...         ...     ...       ...            ...     ...   ...       ...   
23684     23689     984       825            210    20.0    12       8.0   
23685     23690     984       154            210     8.0    13       9.0   
23697     23702     985         1            131    44.0     1       1.0   
23698     23703     985        20              6     7.0     2       2.0   
23699     23704     985         8              6     5.0     5       3.0   
23700     23705     985       830              9    33.0    16       4.0   
23701     23706     985       822            131    77.0     3       5.0   
23702     23707     985       839             10    31.0     6       6.0   
23703     23708     985       832              4    55.0     7       7.0   
23717     23722     986       830              9    33.0     2       1.0   
23718     23723     986       822            131    77.0     4       2.0   
23719     23724     986         8              6     7.0     5       3.0   
23720     23725     986        20              6     5.0     1       4.0   
23737     23742     987        20              6     5.0     2       1.0   
23738     23743     987       822            131    77.0     1       2.0   
23739     23744     987         8              6     7.0     3       3.0   
23740     23745     987         1            131    44.0    20       4.0   
23741     23746     987       830              9    33.0     4       5.0   
23742     23747     987       817              9     3.0    14       6.0   
23743     23748     987        13              3    19.0     9       7.0   
23744     23749     987         4              1    14.

In [8]:
data = AGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed','podtar']]
data.head()

grid  fastestLap  fastestLapTime  fastestLapSpeed  podtar
0     1        39.0        0.001013          218.300       1
1     5        41.0        0.001015          217.586       1
2     7        41.0        0.001020          216.719       1
3    11        58.0        0.001025          215.464       0
4     3        43.0        0.001012          218.385       0

In [9]:
from sklearn.model_selection import train_test_split
X = data[['grid','fastestLap','fastestLapTime','fastestLapSpeed']]
y = data['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [10]:
from sklearn.model_selection import train_test_split
X = data[['grid','fastestLap','fastestLapTime','fastestLapSpeed']]
y = data['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=0, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[404  48]
 [ 64 101]]


In [12]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.82


In [13]:
MGP = results[results['circuitId'] == 2]
MGP = MGP.dropna()
MGP = MGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed','podtar']]
from sklearn.model_selection import train_test_split
X = MGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed']]
y = MGP['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

[[19  1]
 [ 4  8]]
Accuracy of logistic regression classifier on test set: 0.84


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [14]:
BGP = results[results['circuitId'] == 3]
BGP = BGP.dropna()
BGP = BGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed','podtar']]
from sklearn.model_selection import train_test_split
X = BGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed']]
y = BGP['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

[[21  3]
 [ 2  7]]
Accuracy of logistic regression classifier on test set: 0.85


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
SGP = results[results['circuitId'] == 4]
SGP = SGP.dropna()
SGP = SGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed','podtar']]
from sklearn.model_selection import train_test_split
X = SGP[['grid','fastestLap','fastestLapTime','fastestLapSpeed']]
y = SGP['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[13  1]
 [ 5  4]]
Accuracy of logistic regression classifier on test set: 0.74


In [16]:
results.groupby('name').count()

resultId  raceId  driverId  constructorId  \
name                                                                       
Abu Dhabi Grand Prix                196     196       196            196   
Argentine Grand Prix                448     448       448            448   
Australian Grand Prix               790     790       790            790   
Austrian Grand Prix                 741     741       741            741   
Azerbaijan Grand Prix                20      20        20             20   
Bahrain Grand Prix                  280     280       280            280   
Belgian Grand Prix                 1457    1457      1457           1457   
Brazilian Grand Prix               1103    1103      1103           1103   
British Grand Prix                 1733    1733      1733           1733   
Caesars Palace Grand Prix            60      60        60             60   
Canadian Grand Prix                1191    1191      1191           1191   
Chinese Grand Prix                  302     302       302            302   
Dallas Grand Prix                    26      26        26             26   
Detroit Grand Prix                  191     191       191            191   
Dutch Grand Prix                    687     687       687            687   
European Grand Prix                 528     528       528            528   
French Grand Prix                  1404    1404      1404           1404   
German Grand Prix                  1559    1559      1559           1559   
Hungarian Grand Prix                771     771       771            771   
Indian Grand Prix                    70      70        70             70   
Indianapolis 500                    405     405       405            405   
Italian Grand Prix                 1724    1724      1724           1724   
Japanese Grand Prix                 782     782       782            782   
Korean Grand Prix                    94      94        94             94   
Luxembourg Grand Prix                44      44        44             44   
Malaysian Grand Prix                412     412       412            412   
Mexican Grand Prix                  438     438       438            438   
Monaco Grand Prix                  1544    1544      1544           1544   
Moroccan Grand Prix                  25      25        25             25   
Pacific Grand Prix                   52      52        52             52   
Pescara Grand Prix                   16      16        16             16   
Portuguese Grand Prix               413     413       413            413   
Russian Grand Prix                   83      83        83             83   
San Marino Grand Prix               667     667       667            667   
Singapore Grand Prix                218     218       218            218   
South African Grand Prix            581     581       581            581   
Spanish Grand Prix                 1135    1135      1135           1135   
Swedish Grand Prix                  159     159       159            159   
Swiss Grand Prix                    129     129       129            129   
Turkish Grand Prix                  152     152       152            152   
United States Grand Prix            927     927       927            927   
United States Grand Prix West       220     220       220            220   

                               number  grid  position  podtar  dnftar  \
name                                                                    
Abu Dhabi Grand Prix              196   196       168     196     196   
Argentine Grand Prix              448   448       229     448     448   
Australian Grand Prix             790   790       403     790     790   
Austrian Grand Prix               741   741       391     741     741   
Azerbaijan Grand Prix              20    20        14      20      20   
Bahrain Grand Prix                280   280       227     280     280   
Belgian Grand Prix               1457  1457       803    1457    1457   
Brazilian Grand Prix         

In [17]:
coefficients = pd.concat([pd.DataFrame(X.columns),pd.DataFrame(np.transpose(classifier.coef_))], axis = 1)
coefficients

0         0
0             grid -0.497482
1       fastestLap  0.001674
2   fastestLapTime  0.000244
3  fastestLapSpeed  0.009344

In [18]:
from sklearn.model_selection import train_test_split
X = data[['grid','fastestLap','fastestLapTime','fastestLapSpeed']]
y = data['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)
scores

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([1.81356612e+03, 2.69587627e+01, 5.39378531e-04, 3.67483286e+00])

In [19]:
pvalues

array([0.00000000e+00, 2.07842730e-07, 9.81471176e-01, 5.52397920e-02])

In [20]:
from sklearn.model_selection import train_test_split
X = data[['grid']]
y = data['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

[[411  41]
 [ 65 100]]
Accuracy of logistic regression classifier on test set: 0.83


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [21]:
from sklearn.model_selection import train_test_split
X = data[['fastestLap','fastestLapTime','fastestLapSpeed']]
y = data['podtar']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state=0)
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(classifier.score(X_test, y_test)))

[[452   0]
 [165   0]]
Accuracy of logistic regression classifier on test set: 0.73


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [22]:
IGPq = qualifying.merge(races, on='raceId', how='left')
IGPq = IGPq[IGPq['circuitId'] == 14]
IGPq
IGPq

Unnamed: 0  qualifyId  raceId  driverId  constructorId  number  \
268          268        269      31        20              5      15   
269          269        270      31         5              1      23   
270          270        271      31        17              9      10   
271          271        272      31         7              5      14   
272          272        273      31         3              3       7   
273          273        274      31        13              6       2   
274          274        275      31        15              7      11   
275          275        276      31         4              4       5   
276          276        277      31        10              7      12   
277          277        278      31         2              2       3   
278          278        279      31         9              2       4   
279          279        280      31        21             10      21   
280          280        281      31        14              9       9   
281          281        282      31         8              6       1   
282          282        283      31         1              1      22   
283          283        284      31        22             11      17   
284          284        285      31        12              4       6   
285          285        286      31         6              3       8   
286          286        287      31        18             11      16   
287          287        288      31        16             10      20   
632          632        633      48         4              1       1   
633          633        634      48         1              1       2   
634          634        635      48        13              6       5   
635          635        636      48         2              2       9   
636          636        637      48         8              6       6   
637          637        638      48         9              2      10   
638          638        639      48         5              4       4   
639          639        640      48         3              3      16   
640          640        641      48        15              7      12   
641          641        642      48        18             11       7   
...          ...        ...     ...       ...            ...     ...   
6954        6954       6977     961       154            210       8   
6955        6955       6978     961         4              1      14   
6956        6956       6979     961       836            209      94   
6957        6957       6980     961        18              1      22   
6958        6958       6981     961       832              5      55   
6959        6959       6982     961       826              5      26   
6960        6960       6983     961       831             15      12   
6961        6961       6984     961       828             15       9   
6962        6962       6985     961       835              4      30   
6963        6963       6986     961       825              4      20   
7357        7357       7380     981         1            131      44   
7358        7358       7381     981       830              9      33   
7359        7359       7382     981       817              9       3   
7360        7360       7383     981       840              3      18   
7361        7361       7384     981       839             10      31   
7362        7362       7385     981       822            131      77   
7363        7363       7386     981         8              6       7   
7364        7364       7387     981        20              6       5   
7365        7365       7388     981        13              3      19   
7366        7366       7389     981       838              1       2   
7367        7367       7390     981       815             10      11   
7368        7368       7391     981       807              4      27   
7369        7369       7392     981         4              1      14   
7370        7370       7393     981       826 

In [23]:
IGP = results[results['circuitId'] == 14]
IGP = IGP[IGP['dnftar'] == 0]
IGP = IGP.dropna()
IGP

resultId  raceId  driverId  constructorId  number  grid  position  \
268         269      31        20              5    15.0     1       1.0   
269         270      31         5              1    23.0     2       2.0   
270         271      31         9              2     4.0    11       3.0   
271         272      31         4              4     5.0     8       4.0   
272         273      31         2              2     3.0    10       5.0   
273         274      31        13              6     2.0     6       6.0   
274         275      31         1              1    22.0    15       7.0   
275         276      31        17              9    10.0     3       8.0   
276         277      31         8              6     1.0    14       9.0   
277         278      31        12              4     6.0    17      10.0   
278         279      31        10              7    12.0     9      11.0   
279         280      31         6              3     8.0    18      12.0   
280         281      31        15              7    11.0     7      13.0   
281         282      31         3              3     7.0     5      14.0   
282         283      31        18             11    16.0    19      15.0   
632         633      48         4              1     1.0     1       1.0   
633         634      48         1              1     2.0     2       2.0   
634         635      48         8              6     6.0     5       3.0   
635         636      48         2              2     9.0     4       4.0   
636         637      48         9              2    10.0     6       5.0   
637         638      48         3              3    16.0     8       6.0   
638         639      48         5              4     4.0     7       7.0   
639         640      48        18             11     7.0    10       8.0   
640         641      48        17              9    15.0    11       9.0   
641         642      48        22             11     8.0    12      10.0   
642         643      48        15              7    12.0     9      11.0   
1050       1051      67        30              6     5.0     2       1.0   
1051       1052      67         8              1     3.0     1       2.0   
1052       1053      67         9              2    17.0     6       3.0   
1053       1054      67        21              4     2.0     9       4.0   
...         ...     ...       ...            ...     ...   ...       ...   
22399     22403     912         8              6     7.0    11       9.0   
22400     22404     912       825              1    20.0     5      10.0   
22401     22405     912       826              5    26.0    21      11.0   
22402     22406     912       807             10    27.0    13      12.0   
22403     22407     912       818              5    25.0    12      13.0   
22752     22756     938         1            131    44.0     1       1.0   
22753     22757     938        20              6     5.0     3       2.0   
22754     22758     938        13              3    19.0     5       3.0   
22755     22759     938       822              3    77.0     6       4.0   
22756     22760     938         8              6     7.0     2       5.0   
22757     22761     938       815             10    11.0     7       6.0   
23198     23203     961         3            131     6.0     2       1.0   
23199     23204     961         1            131    44.0     1       2.0   
23200     23205     961        20              6     5.0     3       3.0   
23201     23206     961         8              6     7.0     4       4.0   
23202     23207     961       817              9     3.0     6       5.0   
23203     23208     961       822              3    77.0     5       6.0   
23204     23209     961       830              9    33.0     7       7.0   
23205     23210     961       815             10    11.0     8       8.0   
23206     23211     961        13              3    19.0    11       9.0   
23207     23212     961       807             10    27.

In [26]:
IGPavg = IGPq.groupby('year').mean()
IGPavg.head()

Unnamed: 0  qualifyId  raceId   driverId  constructorId     number  \
year                                                                       
1994      2866.5     2868.5   268.0  77.384615      19.923077  16.153846   
1995      2459.5     2461.5   251.0  67.166667      18.416667  15.541667   
2003      4028.5     4030.5   121.0  30.100000      10.600000  10.900000   
2004      1407.5     1408.5   104.0  25.150000      10.600000  10.900000   
2005      1307.5     1308.5    85.0  23.650000       9.600000  10.900000   

      position       q1Milli  q2Milli  q3Milli  round  circuitId  
year                                                              
1994      13.5  85930.769231      0.0      0.0   12.0       14.0  
1995      12.5  87970.833333      0.0      0.0   12.0       14.0  
2003      10.5  83790.000000      0.0      0.0   14.0       14.0  
2004      10.5  81690.000000      0.0      0.0   15.0       14.0  
2005      10.5  82730.000000      0.0      0.0   15.0       14.0

In [28]:
IGPg = IGPq.merge(IGPavg, on='year', how='left')
#IGPg = IGPg['position_x', 'q1Milli_x']#,'q2_x','q3_x','q1_y','q2_y','q3_y']
#IGPq = IGPq.dropna()
IGPg.head()

Unnamed: 0_x  qualifyId_x  raceId_x  driverId_x  constructorId_x  number_x  \
0           268          269        31          20                5        15   
1           269          270        31           5                1        23   
2           270          271        31          17                9        10   
3           271          272        31           7                5        14   
4           272          273        31           3                3         7   

   position_x       q1       q2       q3  ...  raceId_y  driverId_y  \
0           1  01:35.5  01:35.8  01:37.6  ...      31.0       11.15   
1           2  01:35.2  01:35.8  01:37.6  ...      31.0       11.15   
2           3  01:36.0  01:36.3  01:38.1  ...      31.0       11.15   
3           4  01:35.5  01:36.2  01:38.4  ...      31.0       11.15   
4           5  01:35.5  01:35.9  01:38.8  ...      31.0       11.15   

   constructorId_y  number_y  position_y  q1Milli_y q2Milli_y q3Milli_y  \
0              5.8      11.3        10.5    96040.0   72490.0   49405.0   
1              5.8      11.3        10.5    96040.0   72490.0   49405.0   
2              5.8      11.3        10.5    96040.0   72490.0   49405.0   
3              5.8      11.3        10.5    96040.0   72490.0   49405.0   
4              5.8      11.3        10.5    96040.0   72490.0   49405.0   

  round_y circuitId_y  
0    14.0        14.0  
1    14.0        14.0  
2    14.0        14.0  
3    14.0        14.0  
4    14.0        14.0  

[5 rows x 32 columns]

In [113]:
export_csv = IGPg.to_csv ('export_dataframe.csv', index = None, header=True) 
#export_csv - do not run again or it will overwrite

PermissionError: [Errno 13] Permission denied: 'export_dataframe.csv'

In [65]:
good = pd.read_csv("export_dataframe.csv", sep=',', encoding='latin-1')
good

Unnamed: 0_x  qualifyId_x  raceId_x  driverId_x  constructorId_x  \
0             268          269        31          20                5   
1             269          270        31           5                1   
2             270          271        31          17                9   
3             271          272        31           7                5   
4             272          273        31           3                3   
5             273          274        31          13                6   
6             274          275        31          15                7   
7             275          276        31           4                4   
8             276          277        31          10                7   
9             277          278        31           2                2   
10            278          279        31           9                2   
11            279          280        31          21               10   
12            280          281        31          14                9   
13            281          282        31           8                6   
14            282          283        31           1                1   
15            283          284        31          22               11   
16            284          285        31          12                4   
17            285          286        31           6                3   
18            286          287        31          18               11   
19            287          288        31          16               10   
20            632          633        48           4                1   
21            633          634        48           1                1   
22            634          635        48          13                6   
23            635          636        48           2                2   
24            636          637        48           8                6   
25            637          638        48           9                2   
26            638          639        48           5                4   
27            639          640        48           3                3   
28            640          641        48          15                7   
29            641          642        48          18               11   
..            ...          ...       ...         ...              ...   
340          6954         6977       961         154              210   
341          6955         6978       961           4                1   
342          6956         6979       961         836              209   
343          6957         6980       961          18                1   
344          6958         6981       961         832                5   
345          6959         6982       961         826                5   
346          6960         6983       961         831               15   
347          6961         6984       961         828               15   
348          6962         6985       961         835                4   
349          6963         6986       961         825                4   
350          7357         7380       981           1              131   
351          7358         7381       981         830                9   
352          7359         7382       981         817                9   
353          7360         7383       981         840                3   
354          7361         7384       981         839               10   
355          7362         7385       981         822              131   
356          7363         7386       981           8                6   
357          7364         7387       981          20                6   
358          7365         7388       981          13                3   
359          7366         7389       981         838                1   
360          7367         7390       981         815               10   
361          7368         7391       981         807                4   
362          7369         7392       981           4           

In [57]:
#this model will always predict 5
from sklearn.model_selection import train_test_split
X = good[['q1.2', 'q2.2','q3.2']]
y = good['position_x']
X_train, X_test, y_train, y_test = train_test_split(X, y)
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)
print(classifier.coef_)
print(classifier.intercept_)
print(classifier.predict(np.array([[good['q1.2'][5], good['q2.2'][5],good['q3.2'][5]]])))

[1.26315705e-04 6.99516882e-05 9.31006358e-05]
-6.205238823102395
[5.36516525]


In [44]:
classifier.coef_[0]

0.00016838178465171825

In [42]:
classifier.intercept_

-1.4335157565124046

In [133]:
from sklearn.model_selection import train_test_split
X = good[['q1.2']]
y = good['position_x']
X_train, X_test, y_train, y_test = train_test_split(X, y)
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)

array([5571.89977009])

In [45]:
from sklearn.model_selection import train_test_split
X = good[['q1Milli_x']]
y = good['position_x']
X_train, X_test, y_train, y_test = train_test_split(X, y)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [72]:
good['position_x'].count()

370

In [82]:
from sklearn.model_selection import train_test_split
X = good[['q1.4']]
y = good['position_x']
X_train, X_test, y_train, y_test = train_test_split(X, y)
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(X_train, y_train)
from sklearn.feature_selection import chi2
scores, pvalues = chi2(X_train,y_train)
print(classifier.coef_)
print(classifier.intercept_)
print(classifier.predict(np.array([good['q1.4'][[0]]])))
accuracy = classifier.score(X_test,y_test)
print(accuracy*100,'%')

[-0.00015435]
14.609919501663256
[11.43966731]
4.195337958343215 %
